shoppingstore/Controllers/ShoppingCartController.cs
using shoppingstore.Models;
using shoppingstore.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace shoppingstore.Controllers
{
    public class ShoppingCartController : Controller
    {
        ShoppingStoreEntities storeDB = new ShoppingStoreEntities();
        
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            
            return View(viewModel);
        }
        
        public ActionResult AddToCart(int id)
        {
            
            var addedItem = storeDB.Items
                .Single(item => item.ItemId == id);

            
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedItem);

            
            return RedirectToAction("Index");
        }
        
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            
            var cart = ShoppingCart.GetCart(this.HttpContext);

            
            string itemName = storeDB.Carts
                .Single(item => item.RecordId == id).Item.Title;

            
            int itemCount = cart.RemoveFromCart(id);

            
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(itemName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

shoppingstore/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using shoppingstore.Models;
namespace shoppingstore.Controllers
{
    public class StoreController : Controller
    {
        ShoppingStoreEntities storeDB = new ShoppingStoreEntities();
        // GET: Store
        public ActionResult Index()
        {
            var categories = storeDB.Categories.ToList();
            
            return View(categories);
        }
        [ChildActionOnly]
        public ActionResult CategoryMenu()
        {
            var categories = storeDB.Categories.ToList();
            return PartialView(categories);

        }
        public ActionResult Browse(string category)
        {
            var categoryModel = storeDB.Categories.Include("Items")
                .Single(c=>c.Name==category);
            return View(categoryModel);
        }
        public ActionResult Details(int id)
        {
            var Item = storeDB.Items.Find(id);
            return View(Item);
        }
    }
}

shoppingstore/Views/Store/Browse.cshtml
@model shoppingstore.Models.Category

@{
    ViewBag.Title = "Browse";
}
<h2>Browsing Category:@Model.Name</h2>



<ul>
    @foreach (var item in Model.Items)
    {
        <li>
            @Html.ActionLink(item.Title, "Details", new { id = item.ItemId })
        </li>
    }
</ul>

shoppingstore/Views/Store/CategoryMenu.cshtml
@model IEnumerable<shoppingstore.Models.Category>




        @foreach (var category in Model)
        {

            <p class="btn">
                @Html.ActionLink(category.Name, "Browse", "Store", new { Category = category.Name }, null)

                </p>

         }

shoppingstore/Views/Store/Details.cshtml
@model shoppingstore.Models.Item
@{
    ViewBag.Title = "Item - " + Model.Title;
}
<h2>@Model.Title</h2>
<p>
    <img alt="@Model.Title"
       style="width:300px; height:200px;"  src="@Model.ItemArtUrl" />
</p>
<div id="item-details">
    <p>
        <em>Category:</em>
        @Model.Category.Name
    </p>
    <p>
        <em>Producer:</em>
        @Model.Producer.Name
    </p>
    <p>
        <em>Price:</em>
        @String.Format("{0:F}",
Model.Price)
    </p>
    <p class="button1">
        @Html.ActionLink("Add to cart", "AddToCart",
        "ShoppingCart", new { id = Model.ItemId }, "")
    </p>
    <div class="fb-comments"  data-width="230" data-numposts="5"></div>
</div>

shoppingstore/Views/Store/Index.cshtml
@model IEnumerable<shoppingstore.Models.Category>

@{
    ViewBag.Title = "Store";
}

<h2>Browse Category</h2>
<p>

    Select from @Model.Count()
    categories:
</p>
<ul>
    @foreach (var category in Model){
    <li>@Html.ActionLink(category.Name,"Browse",new { category = category.Name })</li>
    }

</ul>
 